version: "3.9"

services:
  blocky:
    image: spx01/blocky:latest
    restart: always
    container_name: blocky
    user: 0:0
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      proxy:
        ipv4_address: 172.18.0.53
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=UTC
    volumes:
      - ./etc/config.yml:/app/config.yml

networks:
  proxy:
    external: true
